image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - cd backend
  - npm install
  - npm start
  - cd .. 
  - npm install  
  - npm run build
  - npm start
build: off  # отключаем встроенную в appveyor систему сборки


deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name saetovdinar
  - git config --global user.email saetonskie@mail.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"